### ISSUE TITLE
Crash when tapping posts repeatedly

### ISSUE THREAD

**Issue by triodan** [Mishiranu/Dashchan#140]
Device is Xiaomi Redmi 3 Pro, running MIUI 8.1.2.0, Android 6.0.1.

Crash happens when viewing any thread, and tapping on a post twice in quick succession. Crash not specific to a single chan.

**Comment by IWillRedPillYou** [comment]
Weird I don't have this problem. What image board extension are you using

**Comment by Mishiranu** [comment]
Can you provide a log as described [here](https://github.com/Mishiranu/Dashchan/wiki/Home-EN#the-app-crashes)?

**Comment by Triodan** [comment]
```Device: Xiaomi kenzo (Redmi Note 3)
SDK: 23 (6.0.1)
Application: 1033 (2.10.1)
----------------------------------------
java.lang.ArrayIndexOutOfBoundsException: length=0; index=-1
	at java.util.ArrayList.get(ArrayList.java:310)
	at com.android.internal.view.menu.ActionMenu.findItem(ActionMenu.java:141)
	at com.mishiranu.dashchan.widget.CommentTextView$CustomSelectionCallback.onCreateActionMode(CommentTextView.java:385)
	at android.widget.Editor.startSelectionActionModeInternal(Editor.java:1759)
	at android.widget.Editor.startSelectionActionMode(Editor.java:1712)
	at android.widget.Editor$SelectionModifierCursorController.onTouchEvent(Editor.java:5404)
	at android.widget.Editor.onTouchEvent(Editor.java:1198)
	at android.widget.TextView.onTouchEvent(TextView.java:8309)
	at com.mishiranu.dashchan.widget.CommentTextView.onTouchEvent(CommentTextView.java:623)
	at com.mishiranu.dashchan.widget.CommentTextView.sendFakeMotionEvent(CommentTextView.java:252)
	at com.mishiranu.dashchan.widget.CommentTextView.startSelection(CommentTextView.java:306)
	at com.mishiranu.dashchan.widget.CommentTextView.startSelection(CommentTextView.java:319)
	at com.mishiranu.dashchan.ui.navigator.manager.ViewUnit.handlePostForDoubleClick(ViewUnit.java:984)
	at com.mishiranu.dashchan.ui.navigator.manager.InteractionUnit.handlePostClick(InteractionUnit.java:359)
	at com.mishiranu.dashchan.ui.navigator.page.PostsPage.onItemClick(PostsPage.java:274)
	at com.mishiranu.dashchan.ui.navigator.NavigatorActivity.onItemClick(NavigatorActivity.java:690)
	at android.widget.AdapterView.performItemClick(AdapterView.java:310)
	at android.widget.AbsListView.performItemClick(AbsListView.java:1145)
	at android.widget.AbsListView$PerformClick.run(AbsListView.java:3081)
	at android.widget.AbsListView$3.run(AbsListView.java:3947)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:148)
	at android.app.ActivityThread.main(ActivityThread.java:5441)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:738)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:628)```

**Comment by Mishiranu** [comment]
This crash seems strange for me. It's definitely something MIUI-related.
https://github.com/Mishiranu/Dashchan/commit/a9d6d36dedccf48884c252cbb554952b6e31cd98 this should fix your problem in next release.
