### ISSUE TITLE
Diochan post problem

### ISSUE THREAD

**Issue by Leproide** [Mishiranu/Dashchan#155]
Hi, cant post on diochan.com

You can use /int/ board for testing because other board are only for Italian IP
http://www.diochan.com/int/

Can you fix please?

**Comment by Mishiranu** [comment]
I just tested it and it seems that posting works well. I don't know how to reproduce the issue.

**Comment by Leproide** [comment]
The extension use a kind of proxy or other?
Because /b/ is only for italian ip.
"Invalid server response" is the error

**Comment by Mishiranu** [comment]
No, I tried to post in `int`.

Can you install [this](https://github.com/Mishiranu/Dashchan/files/1167664/DashchanDiochan-debug.zip) extension and capture the log on posting (see the wiki how to do that)? Don't forget to rename the file (it's the apk file)!

**Comment by Leproide** [comment]
`00:04:48.091: "Diochan response" "<meta http-equiv="refresh" content="0;url=http://www.pastachan.com/" />"
----------------------------------------
Device: motorola falcon_umts (Moto G)
SDK: 25 (7.1.2)
Application: 1033 (2.10.1)
----------------------------------------
chan.content.InvalidResponseException
	at com.mishiranu.dashchan.chan.diochan.DiochanChanPerformer.onSendPost(DiochanChanPerformer.java:241)
	at chan.content.ChanPerformer$Safe.onSendPost(ChanPerformer.java:1145)
	at com.mishiranu.dashchan.content.async.SendPostTask.doInBackground(SendPostTask.java:159)
	at com.mishiranu.dashchan.content.async.SendPostTask.doInBackground(SendPostTask.java:41)
	at com.mishiranu.dashchan.content.async.HttpHolderTask.doInBackground(HttpHolderTask.java:28)
	at android.os.AsyncTask$2.call(AsyncTask.java:305)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
	at java.lang.Thread.run(Thread.java:761)
----------------------------------------
00:06:22.502: "Diochan response" "<meta http-equiv="refresh" content="0;url=http://www.pastachan.com/" />"
----------------------------------------
Device: motorola falcon_umts (Moto G)
SDK: 25 (7.1.2)
Application: 1033 (2.10.1)
----------------------------------------
chan.content.InvalidResponseException
	at com.mishiranu.dashchan.chan.diochan.DiochanChanPerformer.onSendPost(DiochanChanPerformer.java:241)
	at chan.content.ChanPerformer$Safe.onSendPost(ChanPerformer.java:1145)
	at com.mishiranu.dashchan.content.async.SendPostTask.doInBackground(SendPostTask.java:159)
	at com.mishiranu.dashchan.content.async.SendPostTask.doInBackground(SendPostTask.java:41)
	at com.mishiranu.dashchan.content.async.HttpHolderTask.doInBackground(HttpHolderTask.java:28)
	at android.os.AsyncTask$2.call(AsyncTask.java:305)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
	at java.lang.Thread.run(Thread.java:761)
----------------------------------------
00:06:24.342: "Diochan response" "<meta http-equiv="refresh" content="0;url=http://www.pastachan.com/" />"
----------------------------------------
Device: motorola falcon_umts (Moto G)
SDK: 25 (7.1.2)
Application: 1033 (2.10.1)
----------------------------------------
chan.content.InvalidResponseException
	at com.mishiranu.dashchan.chan.diochan.DiochanChanPerformer.onSendPost(DiochanChanPerformer.java:241)
	at chan.content.ChanPerformer$Safe.onSendPost(ChanPerformer.java:1145)
	at com.mishiranu.dashchan.content.async.SendPostTask.doInBackground(SendPostTask.java:159)
	at com.mishiranu.dashchan.content.async.SendPostTask.doInBackground(SendPostTask.java:41)
	at com.mishiranu.dashchan.content.async.HttpHolderTask.doInBackground(HttpHolderTask.java:28)
	at android.os.AsyncTask$2.call(AsyncTask.java:305)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
	at java.lang.Thread.run(Thread.java:761)
----------------------------------------`

**Comment by Mishiranu** [comment]
That's strange. The server response is empty.

I don't know what I've done wrong. I recall I tried to fix it somehow trying to send messages from Italian proxies about a year ago but didn't succeed. Without a good connection from Italian IPs I can't fix it.

**Comment by Leproide** [comment]
I try to contact Diocan's administrator for help you with this bug.
Sorry for my bad english and thank you!

**Comment by Leproide** [comment]
W8, see this:
>00:06:24.342: "Diochan response" "<meta http-equiv="refresh" content="0;url=http://www.pastachan.com/" />"

Wtf? Pastachan.com?

**Comment by Mishiranu** [comment]
Yes, I saw this too. Actually I don't know what to do with it.
