### ISSUE TITLE
Dashchan крашится при попытке открыть тред

### ISSUE THREAD

**Issue by s1q** [Mishiranu/Dashchan#232]
Пытаюсь открыть тред на дваче в b, тред открываются нормально, но потом в один момент при попытке открыть какой-то тред программа вылетает. У меня 9 андроид, заметил эту ошибку на многих прошивках 9 андроида.

Ошибка:
FATAL EXCEPTION: main
Process: com.mishiranu.dashchan, PID: 11370
android.view.WindowManager$BadTokenException: Unable to add window -- token android.os.BinderProxy@6c6548e is not valid; is your activity running?
	at android.view.ViewRootImpl.setView(ViewRootImpl.java:798)
	at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:356)
	at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:93)
	at android.app.Dialog.show(Dialog.java:329)
	at com.mishiranu.dashchan.util.DialogMenu.show(DialogMenu.java:139)
	at com.mishiranu.dashchan.ui.gallery.PagerUnit.displayPopupMenu(PagerUnit.java:666)
	at com.mishiranu.dashchan.ui.gallery.PagerUnit.access$400(PagerUnit.java:54)
	at com.mishiranu.dashchan.ui.gallery.PagerUnit$1.onLongClick(PagerUnit.java:386)
	at com.mishiranu.dashchan.widget.PhotoView.onLongPress(PhotoView.java:401)
	at com.mishiranu.dashchan.widget.PhotoView.access$400(PhotoView.java:46)
	at com.mishiranu.dashchan.widget.PhotoView$1.onLongPress(PhotoView.java:130)
	at android.view.GestureDetector.dispatchLongPress(GestureDetector.java:779)
	at android.view.GestureDetector.access$200(GestureDetector.java:40)
	at android.view.GestureDetector$GestureHandler.handleMessage(GestureDetector.java:293)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6718)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

Полный файл логката у вас в телеге.

**Comment by Mishiranu** [comment]
А вылетает ли в 3.0.0?

**Comment by s1q** [comment]
> 
> 
> А вылетает ли в 3.0.0?

вроде больше не замечал за пару дней, хотя раньше сыпалось очень часто. отпишу, если замечу.
